name: Create Release

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

concurrency: release

jobs:
  pr-build:
    name: Create Release
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: write
      repository-projects: write
    steps:
      - uses: actions/checkout@v3
      - name: Fetch tags
        run: git fetch --tags origin
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Create Release Version
        run: echo "RELEASE_VERSION=v${{github.run_number}}-${GITHUB_SHA::7}" >> $GITHUB_ENV
      - name: Create Release Tag
        run: git tag ${{env.RELEASE_VERSION}}
      - name: Test
        uses: gradle/gradle-build-action@v2
        with:
          arguments: check
      - name: Build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: clean build
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build & Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/deployinator:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/deployinator:${{env.RELEASE_VERSION}}
          push: true
      - name: Push Release Tag
        run: git push origin ${{env.RELEASE_VERSION}}
      - name: Deploy to Digital Ocean
        uses: digitalocean/app_action@main
        with:
          app_name: ${{ secrets.DIGITALOCEAN_APP_NAME }}
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          images: '[
            {
              "name": "deployinator-component",
              "image":{
                "registry": "${{ secrets.DOCKERHUB_USERNAME }}",
                "registry_type": "DOCKER_HUB",
                "repository": "deployinator",
                "tag": "${{env.RELEASE_VERSION}}"
              }
            }
          ]'
